"""epic5_flights_expenses

Revision ID: 70b45ee99f9c
Revises: c8f0af0878b9
Create Date: 2026-08-17 23:32:18.750737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b45ee99f9c'
down_revision: Union[str, None] = 'c8f0af0878b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
