"""Add favorites and extend place model

Revision ID: c8f0af0878b9
Revises: a1b2c3d4e5f6
Create Date: 2026-08-17 21:56:49.666330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f0af0878b9'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('country', sa.String(), nullable=True))
    op.add_column('places', sa.Column('photo_reference', sa.String(), nullable=True))
    op.add_column('places', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('places', sa.Column('user_ratings_total', sa.Integer(), nullable=True))
    op.add_column('places', sa.Column('primary_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'primary_type')
    op.drop_column('places', 'user_ratings_total')
    op.drop_column('places', 'rating')
    op.drop_column('places', 'photo_reference')
    op.drop_column('places', 'country')
    # ### end Alembic commands ###
