"""add_google_auth

Revision ID: d3d04d65ca78
Revises: 2007c8c5c139
Create Date: 2026-08-17 07:34:40.225084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d04d65ca78'
down_revision: Union[str, None] = '2007c8c5c139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('share_token', sa.String(), nullable=True))
    with op.batch_alter_table("trips") as batch_op:
        batch_op.create_unique_constraint("uq_trips_share_token", ["share_token"])
    op.add_column('users', sa.Column('google_sub', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('picture_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_column('users', 'picture_url')
    op.drop_column('users', 'name')
    op.drop_column('users', 'google_sub')
    op.drop_constraint(None, 'trips', type_='unique')
    op.drop_column('trips', 'share_token')
    # ### end Alembic commands ###
